image: docker:latest

check:
  image: adoptjdk11:latest
  stage: test
  except:
    - prod
  script:
    - export GRADLE_USER_HOME=/cache/gradle
    - ./gradlew clean check --stacktrace
stages:
  - test

test:
  stage: test
  image: openjdk:11-jdk-slim
  script:
    - ./gradlew test
    - cat build/reports/jacoco/test/html/index.html
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
