package com.spd.baraholka.notification.enumes;

public enum EventTypes {
    NEW_ADVERTISEMENT,
    ACCOUNT_BAN,
    ADVERTISEMENT_BLOCK,
    NEW_COMMENTS_ADVERTISEMENT,
    NEW_MESSAGE_DIRECT,
    NEW_COMMENTS_TO_MY_COMMENTS,
    CHANGES_ADVERTISEMENT

}
